#!/bin/bash
# Deployment script for N1O1 Clinical Trials
# This script prepares the app for deployment with optimized settings

echo "===== N1O1 Clinical Trials Deployment Preparation ====="

# Apply the redirect fixes
echo "Applying critical redirect fixes..."
python fix_redirects_simple.py

# Create optimized environment variables for deployment
echo "Creating optimized environment variables..."
cat > .env << EOF
# N1O1 Clinical Trials Production Environment
# Auto-generated by deploy.sh

# Port configuration - deployment uses PORT from environment
FLASK_RUN_PORT=5000

# Flask configuration
FLASK_APP=main.py
FLASK_ENV=production
FLASK_DEBUG=0

# Performance settings
GUNICORN_WORKERS=2
GUNICORN_TIMEOUT=300
GUNICORN_KEEP_ALIVE=120

# Security settings - critical for preventing redirect loops
SESSION_COOKIE_SECURE=False
PREFERRED_URL_SCHEME=http
SERVER_NAME=

# Logging
LOG_LEVEL=INFO

# Prevent redirect loops
WERKZEUG_RUN_MAIN=true

# Prevent auto-reloading issues
PYTHONUNBUFFERED=1
EOF

# Create a proper Procfile for deployment services like Heroku
echo "Creating Procfile..."
cat > Procfile << EOF
web: gunicorn --bind 0.0.0.0:\$PORT --timeout 300 --workers 2 --keep-alive 120 main:app
EOF

echo "Deployment preparation complete!"
echo "You can now deploy this application to your hosting service."
echo "The application has been configured to prevent redirect loops and cookie issues."